# Generated by Django 4.2.7 on 2024-02-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General_Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_dept', models.CharField(max_length=50)),
                ('std_batch', models.CharField(max_length=50)),
                ('std_name', models.CharField(max_length=50)),
                ('std_id', models.CharField(max_length=50)),
                ('club1', models.CharField(max_length=50)),
                ('club2', models.CharField(max_length=50)),
                ('club3', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['std_dept', 'std_batch', 'std_id'],
            },
        ),
    ]
