# Generated by Django 4.2.7 on 2024-02-08 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=50)),
                ('club_desc', models.TextField(default='', max_length=5000)),
            ],
            options={
                'verbose_name_plural': 'All Clubs',
                'ordering': ['club_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['dept_name'],
            },
        ),
        migrations.CreateModel(
            name='General_Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_batch', models.IntegerField()),
                ('std_name', models.CharField(max_length=50)),
                ('std_id', models.CharField(max_length=50)),
                ('club', models.ManyToManyField(blank=True, related_name='members', to='general.clubs')),
                ('std_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.department')),
            ],
            options={
                'verbose_name_plural': 'General_database',
                'ordering': ['std_dept', 'std_batch', 'std_id'],
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=50)),
                ('std_batch', models.IntegerField()),
                ('std_id', models.CharField(max_length=50)),
                ('std_email', models.EmailField(max_length=254)),
                ('accept_membership', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='general.clubs')),
                ('std_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.department')),
            ],
            options={
                'ordering': ['club'],
            },
        ),
    ]
