# Generated by Django 4.2.7 on 2024-02-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general_database',
            options={'ordering': ['std_dept', 'std_batch', 'std_id'], 'verbose_name_plural': 'General_database'},
        ),
        migrations.AlterField(
            model_name='general_database',
            name='club1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='general_database',
            name='club2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='general_database',
            name='club3',
            field=models.BooleanField(default=False),
        ),
    ]
