# Generated by Django 4.2.7 on 2024-02-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'ordering': ['club'], 'verbose_name_plural': 'Applications'},
        ),
        migrations.AddField(
            model_name='general_database',
            name='std_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
