# Generated by Django 4.2.7 on 2024-02-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_applications_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_database',
            name='std_id',
            field=models.BigIntegerField(),
        ),
    ]
