# Generated by Django 4.2.7 on 2024-02-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_clubs_remove_general_database_club1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='club_desc',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
