# Generated by Django 4.2.7 on 2024-02-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_clubs_club_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['dept_name'],
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_dept', models.CharField(max_length=50)),
                ('std_name', models.CharField(max_length=50)),
                ('std_batch', models.IntegerField()),
                ('std_id', models.CharField(max_length=50)),
                ('std_email', models.EmailField(max_length=254)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.clubs')),
            ],
        ),
    ]
