# Generated by Django 4.2.7 on 2024-02-08 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_department_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='std_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.department'),
        ),
        migrations.AlterField(
            model_name='general_database',
            name='std_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.department'),
        ),
    ]
